# bosses.py

BOSSES = [

    # =========================
    # W1
    # =========================
    {"world": "W1", "layer": "Camada 3", "location": "1F do Templo do Touro Demoníaco", "boss": "Touro Trovejante", "time": "09:00"},
    {"world": "W1", "layer": "Camada 3", "location": "Santuário do Rei dos Touros", "boss": "Rei dos Touros Malvados", "time": "09:00"},
    {"world": "W1", "layer": "Camada 1", "location": "Montanha dos Sete Vales", "boss": "Yaksha dos Olhos Noturnos", "time": "09:30"},
    {"world": "W1", "layer": "Camada 1", "location": "Montanha dos Sete Vales", "boss": "Tatu Gigante de Carapaça Sombria", "time": "09:30"},
    {"world": "W1", "layer": "Camada 3", "location": "Floresta do Touro Malvado", "boss": "Mata", "time": "10:00"},
    {"world": "W1", "layer": "Camada 1", "location": "Ilha do Fogo Ardente", "boss": "Bulhu", "time": "10:30"},
    {"world": "W1", "layer": "Camada 3", "location": "1F do Templo do Touro Demoníaco", "boss": "Touro Trovejante", "time": "11:00"},
    {"world": "W1", "layer": "Camada 1", "location": "Cidade Unseo", "boss": "Jihwa", "time": "11:30"},
    {"world": "W1", "layer": "Camada 3", "location": "Floresta do Touro Malvado", "boss": "Mata", "time": "12:00"},
    {"world": "W1", "layer": "Camada 3", "location": "Santuário do Rei dos Touros", "boss": "Rei dos Touros Malvados", "time": "12:00"},
    {"world": "W1", "layer": "Camada 1", "location": "Montanha dos Sete Vales", "boss": "Tatu Gigante de Carapaça Sombria", "time": "12:30"},
    {"world": "W1", "layer": "Camada 3", "location": "1F do Templo do Touro Demoníaco", "boss": "Touro Trovejante", "time": "13:00"},
    {"world": "W1", "layer": "Camada 3", "location": "Floresta do Touro Malvado", "boss": "Mata", "time": "14:00"},
    {"world": "W1", "layer": "Camada 1", "location": "Cidade Unseo", "boss": "Jihwa", "time": "14:30"},
    {"world": "W1", "layer": "Camada 3", "location": "1F do Templo do Touro Demoníaco", "boss": "Touro Trovejante", "time": "15:00"},
    {"world": "W1", "layer": "Camada 3", "location": "Santuário do Rei dos Touros", "boss": "Rei dos Touros Malvados", "time": "15:00"},
    {"world": "W1", "layer": "Camada 1", "location": "Montanha dos Sete Vales", "boss": "Yaksha dos Olhos Noturnos", "time": "15:30"},
    {"world": "W1", "layer": "Camada 1", "location": "Montanha dos Sete Vales", "boss": "Tatu Gigante de Carapaça Sombria", "time": "15:30"},
    {"world": "W1", "layer": "Camada 3", "location": "Floresta do Touro Malvado", "boss": "Mata", "time": "16:00"},
    {"world": "W1", "layer": "Camada 1", "location": "Ilha do Fogo Ardente", "boss": "Bulhu", "time": "16:30"},
    {"world": "W1", "layer": "Camada 3", "location": "1F do Templo do Touro Demoníaco", "boss": "Touro Trovejante", "time": "17:00"},
    {"world": "W1", "layer": "Camada 1", "location": "Cidade Unseo", "boss": "Jihwa", "time": "17:30"},
    {"world": "W1", "layer": "Camada 3", "location": "Floresta do Touro Malvado", "boss": "Mata", "time": "18:00"},
    {"world": "W1", "layer": "Camada 3", "location": "Santuário do Rei dos Touros", "boss": "Rei dos Touros Malvados", "time": "18:00"},
    {"world": "W1", "layer": "Camada 1", "location": "Montanha dos Sete Vales", "boss": "Tatu Gigante de Carapaça Sombria", "time": "18:30"},
    {"world": "W1", "layer": "Camada 3", "location": "1F do Templo do Touro Demoníaco", "boss": "Touro Trovejante", "time": "19:00"},
    {"world": "W1", "layer": "Camada 3", "location": "Floresta do Touro Malvado", "boss": "Mata", "time": "20:00"},
    {"world": "W1", "layer": "Camada 1", "location": "Cidade Unseo", "boss": "Jihwa", "time": "20:30"},
    {"world": "W1", "layer": "Camada 3", "location": "1F do Templo do Touro Demoníaco", "boss": "Touro Trovejante", "time": "21:00"},
    {"world": "W1", "layer": "Camada 3", "location": "Santuário do Rei dos Touros", "boss": "Rei dos Touros Malvados", "time": "21:00"},
    {"world": "W1", "layer": "Camada 1", "location": "Montanha dos Sete Vales", "boss": "Yaksha dos Olhos Noturnos", "time": "21:30"},
    {"world": "W1", "layer": "Camada 1", "location": "Montanha dos Sete Vales", "boss": "Tatu Gigante de Carapaça Sombria", "time": "21:30"},
    {"world": "W1", "layer": "Camada 3", "location": "Floresta do Touro Malvado", "boss": "Mata", "time": "22:00"},
    {"world": "W1", "layer": "Camada 1", "location": "Ilha do Fogo Ardente", "boss": "Bulhu", "time": "22:30"},
    {"world": "W1", "layer": "Camada 3", "location": "1F do Templo do Touro Demoníaco", "boss": "Touro Trovejante", "time": "23:00"},
    {"world": "W1", "layer": "Camada 1", "location": "Cidade Unseo", "boss": "Jihwa", "time": "23:30"},
    {"world": "W1", "layer": "Camada 3", "location": "Floresta do Touro Malvado", "boss": "Mata", "time": "00:00"},
    {"world": "W1", "layer": "Camada 3", "location": "Santuário do Rei dos Touros", "boss": "Rei dos Touros Malvados", "time": "00:00"},
    {"world": "W1", "layer": "Camada 1", "location": "Montanha dos Sete Vales", "boss": "Tatu Gigante de Carapaça Sombria", "time": "00:30"},
    {"world": "W1", "layer": "Camada 3", "location": "1F do Templo do Touro Demoníaco", "boss": "Touro Trovejante", "time": "01:00"},
    {"world": "W1", "layer": "Camada 3", "location": "Floresta do Touro Malvado", "boss": "Mata", "time": "02:00"},
    {"world": "W1", "layer": "Camada 1", "location": "Cidade Unseo", "boss": "Jihwa", "time": "02:30"},
    {"world": "W1", "layer": "Camada 3", "location": "1F do Templo do Touro Demoníaco", "boss": "Touro Trovejante", "time": "03:00"},
    {"world": "W1", "layer": "Camada 3", "location": "Santuário do Rei dos Touros", "boss": "Rei dos Touros Malvados", "time": "03:00"},
    {"world": "W1", "layer": "Camada 1", "location": "Montanha dos Sete Vales", "boss": "Yaksha dos Olhos Noturnos", "time": "03:30"},
    {"world": "W1", "layer": "Camada 1", "location": "Montanha dos Sete Vales", "boss": "Tatu Gigante de Carapaça Sombria", "time": "03:30"},
    {"world": "W1", "layer": "Camada 3", "location": "Floresta do Touro Malvado", "boss": "Mata", "time": "04:00"},
    {"world": "W1", "layer": "Camada 1", "location": "Ilha do Fogo Ardente", "boss": "Bulhu", "time": "04:30"},
    {"world": "W1", "layer": "Camada 3", "location": "1F do Templo do Touro Demoníaco", "boss": "Touro Trovejante", "time": "05:00"},
    {"world": "W1", "layer": "Camada 1", "location": "Cidade Unseo", "boss": "Jihwa", "time": "05:30"},
    {"world": "W1", "layer": "Camada 3", "location": "Floresta do Touro Malvado", "boss": "Mata", "time": "06:00"},
    {"world": "W1", "layer": "Camada 3", "location": "Santuário do Rei dos Touros", "boss": "Rei dos Touros Malvados", "time": "06:00"},
    {"world": "W1", "layer": "Camada 1", "location": "Montanha dos Sete Vales", "boss": "Tatu Gigante de Carapaça Sombria", "time": "06:30"},
    {"world": "W1", "layer": "Camada 3", "location": "1F do Templo do Touro Demoníaco", "boss": "Touro Trovejante", "time": "07:00"},
    {"world": "W1", "layer": "Camada 3", "location": "Floresta do Touro Malvado", "boss": "Mata", "time": "08:00"},
    {"world": "W1", "layer": "Camada 1", "location": "Cidade Unseo", "boss": "Jihwa", "time": "08:30"},

    # =========================
    # W2
    # =========================
    {"world": "W2", "layer": "Camada 1", "location": "Prisão Subterrânia", "boss": "Molgrash", "time": "10:30"},
    {"world": "W2", "layer": "Camada 3", "location": "Montanha da Lunula de Sangue", "boss": "Juhui", "time": "11:30"},
    {"world": "W2", "layer": "Camada 1", "location": "Campo de Gelo do Dragão Noveno", "boss": "Gwe Mukang", "time": "11:30"},
    {"world": "W2", "layer": "Camada 1", "location": "Palácio do Dragão Noveno", "boss": "Wi Kwangryeong", "time": "11:30"},
    {"world": "W2", "layer": "Camada 1", "location": "Prisão Subterrânia", "boss": "Do Maengryong", "time": "12:30"},
    {"world": "W2", "layer": "Camada 1", "location": "Prisão Subterrânia", "boss": "Molgrash", "time": "13:30"},
    {"world": "W2", "layer": "Camada 3", "location": "Montanha da Lunula de Sangue", "boss": "Juhui", "time": "14:30"},
    {"world": "W2", "layer": "Camada 1", "location": "Palácio do Dragão Noveno", "boss": "Wi Kwangryeong", "time": "14:30"},
    {"world": "W2", "layer": "Camada 1", "location": "Prisão Subterrânia", "boss": "Molgrash", "time": "16:30"},
    {"world": "W2", "layer": "Camada 3", "location": "Montanha da Lunula de Sangue", "boss": "Juhui", "time": "17:30"},
    {"world": "W2", "layer": "Camada 1", "location": "Campo de Gelo do Dragão Noveno", "boss": "Gwe Mukang", "time": "17:30"},
    {"world": "W2", "layer": "Camada 1", "location": "Palácio do Dragão Noveno", "boss": "Wi Kwangryeong", "time": "17:30"},
    {"world": "W2", "layer": "Camada 1", "location": "Prisão Subterrânia", "boss": "Do Maengryong", "time": "18:30"},
    {"world": "W2", "layer": "Camada 1", "location": "Prisão Subterrânia", "boss": "Molgrash", "time": "19:30"},
    {"world": "W2", "layer": "Camada 3", "location": "Montanha da Lunula de Sangue", "boss": "Juhui", "time": "20:30"},
    {"world": "W2", "layer": "Camada 1", "location": "Palácio do Dragão Noveno", "boss": "Wi Kwangryeong", "time": "20:30"},
    {"world": "W2", "layer": "Camada 1", "location": "Prisão Subterrânia", "boss": "Molgrash", "time": "22:30"},
    {"world": "W2", "layer": "Camada 3", "location": "Montanha da Lunula de Sangue", "boss": "Juhui", "time": "23:30"},
    {"world": "W2", "layer": "Camada 1", "location": "Campo de Gelo do Dragão Noveno", "boss": "Gwe Mukang", "time": "23:30"},
    {"world": "W2", "layer": "Camada 1", "location": "Palácio do Dragão Noveno", "boss": "Wi Kwangryeong", "time": "23:30"},

    # =========================
    # W3
    # =========================
    {"world": "W3", "layer": "Camada 3", "location": "Planície das Víboras Monstruosas", "boss": "Imperador Tatu Sombrio", "time": "09:30"},
    {"world": "W3", "layer": "Camada 3", "location": "Túmulo de Rockcut", "boss": "Budu", "time": "09:30"},
    {"world": "W3", "layer": "Camada 3", "location": "Planície das Víboras Monstruosas", "boss": "Imperador Tatu Sombrio", "time": "11:30"},
    {"world": "W3", "layer": "Camada 3", "location": "Túmulo de Rockcut", "boss": "Mara", "time": "11:30"},
    {"world": "W3", "layer": "Camada 3", "location": "Planície das Víboras Monstruosas", "boss": "Imperador Tatu Sombrio", "time": "13:30"},
    {"world": "W3", "layer": "Camada 3", "location": "Necrópole de Nerfariox", "boss": "Gyo", "time": "14:30"},
    {"world": "W3", "layer": "Camada 3", "location": "Túmulo de Rockcut", "boss": "Mara", "time": "14:30"},
    {"world": "W3", "layer": "Camada 3", "location": "Planície das Víboras Monstruosas", "boss": "Imperador Tatu Sombrio", "time": "15:30"},
    {"world": "W3", "layer": "Camada 3", "location": "Túmulo de Rockcut", "boss": "Budu", "time": "15:30"},
    {"world": "W3", "layer": "Camada 3", "location": "Planície das Víboras Monstruosas", "boss": "Imperador Tatu Sombrio", "time": "17:30"},
    {"world": "W3", "layer": "Camada 3", "location": "Túmulo de Rockcut", "boss": "Mara", "time": "17:30"},
    {"world": "W3", "layer": "Camada 3", "location": "Planície das Víboras Monstruosas", "boss": "Imperador Tatu Sombrio", "time": "19:30"},
    {"world": "W3", "layer": "Camada 3", "location": "Necrópole de Nerfariox", "boss": "Gyo", "time": "20:30"},
    {"world": "W3", "layer": "Camada 3", "location": "Túmulo de Rockcut", "boss": "Mara", "time": "20:30"},
    {"world": "W3", "layer": "Camada 3", "location": "Planície das Víboras Monstruosas", "boss": "Imperador Tatu Sombrio", "time": "21:30"},
    {"world": "W3", "layer": "Camada 3", "location": "Túmulo de Rockcut", "boss": "Budu", "time": "21:30"},
    {"world": "W3", "layer": "Camada 3", "location": "Planície das Víboras Monstruosas", "boss": "Imperador Tatu Sombrio", "time": "23:30"},
    {"world": "W3", "layer": "Camada 3", "location": "Túmulo de Rockcut", "boss": "Mara", "time": "23:30"},
    {"world": "W3", "layer": "Camada 3", "location": "Planície das Víboras Monstruosas", "boss": "Imperador Tatu Sombrio", "time": "01:30"},
    {"world": "W3", "layer": "Camada 3", "location": "Necrópole de Nerfariox", "boss": "Gyo", "time": "02:30"},
    {"world": "W3", "layer": "Camada 3", "location": "Túmulo de Rockcut", "boss": "Mara", "time": "02:30"},
    {"world": "W3", "layer": "Camada 3", "location": "Planície das Víboras Monstruosas", "boss": "Imperador Tatu Sombrio", "time": "03:30"},
    {"world": "W3", "layer": "Camada 3", "location": "Túmulo de Rockcut", "boss": "Budu", "time": "03:30"},
    {"world": "W3", "layer": "Camada 3", "location": "Planície das Víboras Monstruosas", "boss": "Imperador Tatu Sombrio", "time": "05:30"},
    {"world": "W3", "layer": "Camada 3", "location": "Túmulo de Rockcut", "boss": "Mara", "time": "05:30"},
    {"world": "W3", "layer": "Camada 3", "location": "Planície das Víboras Monstruosas", "boss": "Imperador Tatu Sombrio", "time": "07:30"},
    {"world": "W3", "layer": "Camada 3", "location": "Necrópole de Nerfariox", "boss": "Gyo", "time": "08:30"},
    {"world": "W3", "layer": "Camada 3", "location": "Túmulo de Rockcut", "boss": "Mara", "time": "08:30"},

    # =========================
    # W4
    # =========================
    {"world": "W4", "layer": "Camada 3", "location": "Círculo de Selo Suzerano", "boss": "Kurilaika", "time": "09:00"},
    {"world": "W4", "layer": "Camada 3", "location": "Deserto da Fantasia", "boss": "Santidade Inabalável Nerfariox", "time": "10:00"},
    {"world": "W4", "layer": "Camada 3", "location": "Deserto da Fantasia", "boss": "Santidade Inabalável Nerfariox", "time": "12:00"},
    {"world": "W4", "layer": "Camada 3", "location": "Círculo de Selo Suzerano", "boss": "Kurilaika", "time": "12:00"},
    {"world": "W4", "layer": "Camada 3", "location": "Deserto da Fantasia", "boss": "Santidade Inabalável Nerfariox", "time": "14:00"},
    {"world": "W4", "layer": "Camada 3", "location": "Círculo de Selo Suzerano", "boss": "Kurilaika", "time": "15:00"},
    {"world": "W4", "layer": "Camada 3", "location": "Deserto da Fantasia", "boss": "Santidade Inabalável Nerfariox", "time": "16:00"},
    {"world": "W4", "layer": "Camada 3", "location": "Deserto da Fantasia", "boss": "Santidade Inabalável Nerfariox", "time": "18:00"},
    {"world": "W4", "layer": "Camada 3", "location": "Círculo de Selo Suzerano", "boss": "Kurilaika", "time": "18:00"},
    {"world": "W4", "layer": "Camada 3", "location": "Deserto da Fantasia", "boss": "Santidade Inabalável Nerfariox", "time": "20:00"},
    {"world": "W4", "layer": "Camada 3", "location": "Círculo de Selo Suzerano", "boss": "Kurilaika", "time": "21:00"},
    {"world": "W4", "layer": "Camada 3", "location": "Deserto da Fantasia", "boss": "Santidade Inabalável Nerfariox", "time": "22:00"},
    {"world": "W4", "layer": "Camada 3", "location": "Deserto da Fantasia", "boss": "Santidade Inabalável Nerfariox", "time": "00:00"},
    {"world": "W4", "layer": "Camada 3", "location": "Círculo de Selo Suzerano", "boss": "Kurilaika", "time": "00:00"},
    {"world": "W4", "layer": "Camada 3", "location": "Deserto da Fantasia", "boss": "Santidade Inabalável Nerfariox", "time": "02:00"},

    # =========================
    # W6
    # =========================
    {"world": "W6", "layer": "Camada 3", "location": "Abismo da Mina Abandonada", "boss": "Hong Yeom Transformada", "time": "09:30"},
    {"world": "W6", "layer": "Camada 3", "location": "Cidade Bicheon", "boss": "Asura", "time": "10:30"},
    {"world": "W6", "layer": "Camada 3", "location": "Cidade Bicheon", "boss": "Cheol Mokgang", "time": "10:30"},
    {"world": "W6", "layer": "Camada 3", "location": "Bosque Fantasma", "boss": "Wuihan", "time": "11:30"},
    {"world": "W6", "layer": "Camada 3", "location": "Abismo da Mina Abandonada", "boss": "Hong Yeom Transformada", "time": "11:30"},
    {"world": "W6", "layer": "Camada 3", "location": "Cidade Bicheon", "boss": "Cheol Mokgang", "time": "12:30"},
    {"world": "W6", "layer": "Camada 3", "location": "Labirinto Bicheon", "boss": "Yeticlops", "time": "12:30"},
    {"world": "W6", "layer": "Camada 3", "location": "Abismo da Mina Abandonada", "boss": "Hong Yeom Transformada", "time": "13:30"},
    {"world": "W6", "layer": "Camada 3", "location": "Cidade Bicheon", "boss": "Cheol Mokgang", "time": "14:30"},
    {"world": "W6", "layer": "Camada 3", "location": "Abismo da Mina Abandonada", "boss": "Hong Yeom Transformada", "time": "15:30"},
    {"world": "W6", "layer": "Camada 3", "location": "Cidade Bicheon", "boss": "Asura", "time": "16:30"},
    {"world": "W6", "layer": "Camada 3", "location": "Cidade Bicheon", "boss": "Cheol Mokgang", "time": "16:30"},
    {"world": "W6", "layer": "Camada 3", "location": "Bosque Fantasma", "boss": "Wuihan", "time": "17:30"},
    {"world": "W6", "layer": "Camada 3", "location": "Abismo da Mina Abandonada", "boss": "Hong Yeom Transformada", "time": "17:30"},
    {"world": "W6", "layer": "Camada 3", "location": "Cidade Bicheon", "boss": "Cheol Mokgang", "time": "18:30"},
    {"world": "W6", "layer": "Camada 3", "location": "Labirinto Bicheon", "boss": "Yeticlops", "time": "18:30"},
    {"world": "W6", "layer": "Camada 3", "location": "Abismo da Mina Abandonada", "boss": "Hong Yeom Transformada", "time": "19:30"},
    {"world": "W6", "layer": "Camada 3", "location": "Cidade Bicheon", "boss": "Cheol Mokgang", "time": "20:30"},
    {"world": "W6", "layer": "Camada 3", "location": "Abismo da Mina Abandonada", "boss": "Hong Yeom Transformada", "time": "21:30"},
    {"world": "W6", "layer": "Camada 3", "location": "Cidade Bicheon", "boss": "Asura", "time": "22:30"},
    {"world": "W6", "layer": "Camada 3", "location": "Cidade Bicheon", "boss": "Cheol Mokgang", "time": "22:30"},
    {"world": "W6", "layer": "Camada 3", "location": "Bosque Fantasma", "boss": "Wuihan", "time": "23:30"},
    {"world": "W6", "layer": "Camada 3", "location": "Abismo da Mina Abandonada", "boss": "Hong Yeom Transformada", "time": "23:30"},

    # =========================
    # W7
    # =========================
    {"world": "W7", "layer": "Camada 3", "location": "Jardim de Taehyul", "boss": "Taehyul", "time": "09:00"},
    {"world": "W7", "layer": "Camada 3", "location": "Jardim de Taehyul", "boss": "Taehyul", "time": "11:00"},
    {"world": "W7", "layer": "Camada 3", "location": "Construção Principal do Culto Demoníaco", "boss": "Yiun", "time": "11:00"},
    {"world": "W7", "layer": "Camada 3", "location": "Jardim de Taehyul", "boss": "Taehyul", "time": "13:00"},
    {"world": "W7", "layer": "Camada 3", "location": "Construção Principal do Culto Demoníaco", "boss": "Yiun", "time": "14:00"},
    {"world": "W7", "layer": "Camada 3", "location": "Jardim de Taehyul", "boss": "Taehyul", "time": "15:00"},
    {"world": "W7", "layer": "Camada 3", "location": "Jardim de Taehyul", "boss": "Taehyul", "time": "17:00"},
    {"world": "W7", "layer": "Camada 3", "location": "Construção Principal do Culto Demoníaco", "boss": "Yiun", "time": "17:00"},
    {"world": "W7", "layer": "Camada 3", "location": "Jardim de Taehyul", "boss": "Taehyul", "time": "19:00"},
    {"world": "W7", "layer": "Camada 3", "location": "Construção Principal do Culto Demoníaco", "boss": "Yiun", "time": "20:00"},
    {"world": "W7", "layer": "Camada 3", "location": "Jardim de Taehyul", "boss": "Taehyul", "time": "21:00"},
    {"world": "W7", "layer": "Camada 3", "location": "Jardim de Taehyul", "boss": "Taehyul", "time": "23:00"},
    {"world": "W7", "layer": "Camada 3", "location": "Construção Principal do Culto Demoníaco", "boss": "Yiun", "time": "23:00"},

    # =========================
    # W8
    # =========================
    {"world": "W8", "layer": "Camada 3", "location": "Círculo de Selo dos Gigantes Brancos", "boss": "Ye Wihuang (Velho)", "time": "09:00"},
    {"world": "W8", "layer": "Camada 3", "location": "Círculo de Selo dos Gigantes Brancos", "boss": "Ye Wihuang (Velho)", "time": "13:00"},
    {"world": "W8", "layer": "Camada 3", "location": "Círculo de Selo dos Gigantes Brancos", "boss": "Ye Wihuang (Velho)", "time": "17:00"},
    {"world": "W8", "layer": "Camada 3", "location": "Círculo de Selo dos Gigantes Brancos", "boss": "Ye Wihuang (Velho)", "time": "21:00"},
    {"world": "W8", "layer": "Camada 3", "location": "Círculo de Selo dos Gigantes Brancos", "boss": "Ye Wihuang (Velho)", "time": "01:00"},
    {"world": "W8", "layer": "Camada 3", "location": "Círculo de Selo dos Gigantes Brancos", "boss": "Ye Wihuang (Velho)", "time": "05:00"},
]