name: MIR4 Timer

on:
  schedule:
    - cron: "* * * * *"

  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    env:
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run bot
        run: |
          python main.py
